name: Publish Webreport

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout default branch
      uses: actions/checkout@v4.2.2
      with:
        sparse-checkout: |
          *.html
        sparse-checkout-cone-mode: false

    - name: Copy html-file to gh-page branch
      uses: actions/upload-pages-artifact@v3 
      with:
        path: '/'
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
