name: Publish Webreport

on:
  workflow_dispatch:

jobs:
  runIt:
    runs-on: ubuntu-latest

    steps:  
    - name: Checkout default branch
      uses: actions/checkout@v4.2.2
      with:
        sparse-checkout: |
          *.html
        sparse-checkout-cone-mode: false

    - name: Rename html-file to index.html
      run: mv *.html index.html

    - name: Copy html-file to gh-page branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: webreport-website
