name: Test

on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]_pre'
  
env:
  zenodo_deposition_id: 1093681
  zenodo_server: 'https://sandbox.zenodo.org'
  whitelist_replace_doi: .github/workflows/.zenodo_whitelist_replace_doi
  whitelist_uploads: .github/workflows/.zenodo_whitelist_uploads
  
jobs:
  createTag:
    name: Create tag from ref
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagName.outputs.tag }}
    
    steps:
      - name: Remove _pre from ref
        id: tagName
        run: |
          REF=${{github.ref_name}}
          TAG="${REF//_pre/}"
          echo "::set-output name=tag::$TAG"
      
      - name: read tag   
        run: echo "env is ${{steps.tagName.outputs.tag}}"
  useEnv:
    name: use env
    runs-on: ubuntu-latest
    needs: [createTag]
    
    steps:
      - name: read env other job   
        run: echo "env is ${{needs.createTag.outputs.tag}}"
