name: Test

on:
  workflow_dispatch:
  #push:
  #  tags:
  #    - '[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]_pre'
  
env:
  zenodo_deposition_id: 1093681
  zenodo_server: 'https://sandbox.zenodo.org'
  whitelist_replace_doi: .github/workflows/.zenodo_whitelist_replace_doi
  whitelist_uploads: .github/workflows/.zenodo_whitelist_uploads
  
jobs:
  replaceTag:
    name: set env
    runs-on: ubuntu-latest
    
    steps:
      - name: test ref
        run: echo ${{github.ref}}
    
      - name: test replace
        run: echo "tag is '(${{github.ref}}//_pre/)'"
      
      - name: Set env tag
        run: echo "tag=$(${{github.ref}}//_pre/)" >> $GITHUB_ENV
      
      - name: read env   
        run: echo "env is ${{env.tag}}"
  useEnv:
    name: use env
    runs-on: ubuntu-latest
    needs: [replaceTag]
    
    steps:
      - name: read env other job   
        run: echo "env is ${{env.tag}}"